// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeSf5kvQNLDyAX-J8svKE-1dYdhHa4Fa4',
    appId: '1:756388383425:web:96d9d479ce8ca8a44ea240',
    messagingSenderId: '756388383425',
    projectId: 'bankingapp-76a24',
    authDomain: 'bankingapp-76a24.firebaseapp.com',
    storageBucket: 'bankingapp-76a24.appspot.com',
    measurementId: 'G-Y0J1Z8VDF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzyPF2ASqTzx0frQzh4ltTFktQP-RXL0',
    appId: '1:756388383425:android:27fa2559f90a86bb4ea240',
    messagingSenderId: '756388383425',
    projectId: 'bankingapp-76a24',
    storageBucket: 'bankingapp-76a24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDlPWcJB-1GxRD2D6C_Qosdqrd_erp7xo',
    appId: '1:756388383425:ios:722ba949fe8b63ad4ea240',
    messagingSenderId: '756388383425',
    projectId: 'bankingapp-76a24',
    storageBucket: 'bankingapp-76a24.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDlPWcJB-1GxRD2D6C_Qosdqrd_erp7xo',
    appId: '1:756388383425:ios:bac5d3e08018db6d4ea240',
    messagingSenderId: '756388383425',
    projectId: 'bankingapp-76a24',
    storageBucket: 'bankingapp-76a24.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
