// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzyPF2ASqTzx0frQzh4ltTFktQP-RXL0',
    appId: '1:756388383425:android:27fa2559f90a86bb4ea240',
    messagingSenderId: '756388383425',
    projectId: 'bankingapp-76a24',
    databaseURL: 'https://bankingapp-76a24-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bankingapp-76a24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDlPWcJB-1GxRD2D6C_Qosdqrd_erp7xo',
    appId: '1:756388383425:ios:722ba949fe8b63ad4ea240',
    messagingSenderId: '756388383425',
    projectId: 'bankingapp-76a24',
    databaseURL: 'https://bankingapp-76a24-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bankingapp-76a24.appspot.com',
    iosClientId: '756388383425-th6kpf829inhg70fevbop5bajivaoo2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
